import { NextResponse, type NextRequest } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'
import type { Tables } from '@/types/supabase'

export const dynamic = 'force-dynamic'

type CharacterWithRelations = Tables<'characters'> & {
  attributes: Tables<'attributes'>[]
  skills: Tables<'skills'>[]
  abilities: Tables<'abilities'>[]
}

export async function GET(request: NextRequest) {
  const authHeader = request.headers.get('authorization')
  const expectedSecret = process.env.EXPORT_SECRET
  if (expectedSecret && authHeader !== `Bearer ${expectedSecret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = createServiceClient()

  const [charactersResult] = await Promise.all([
    supabase
      .from('characters')
      .select('*, attributes(*), skills(*), abilities(*)')
      .is('deleted_at', null)
      .order('nome'),
  ])

  if (charactersResult.error) {
    return NextResponse.json({ error: charactersResult.error.message }, { status: 500 })
  }

  const characters = (charactersResult.data ?? []) as unknown as CharacterWithRelations[]

  const players = characters.filter((c) => c.entity_type === 'player')
  const npcs = characters.filter((c) => c.entity_type === 'npc')

  // Build data.js compatible format
  const playerData: Record<string, unknown> = {}
  for (const player of players) {
    playerData[player.slug] = {
      id: player.id,
      nome: player.nome,
      nivel: player.nivel,
      xp: player.xp,
      arquetipo: player.arquetipo,
      idade: player.idade,
      altura: player.altura,
      peso: player.peso,
      classe_social: player.classe_social,
      inspiracao: player.inspiracao,
      discord_id: player.discord_id,
      pv_max: player.pv_max,
      ps_max: player.ps_max,
      extra_info: player.extra_info,
      attributes: (player.attributes as unknown[]) ?? [],
      skills: (player.skills as unknown[]) ?? [],
      abilities: (player.abilities as unknown[]) ?? [],
    }
  }

  const npcData: Record<string, unknown> = {}
  for (const npc of npcs) {
    npcData[npc.slug] = {
      id: npc.id,
      nome: npc.nome,
      nivel: npc.nivel,
      arquetipo: npc.arquetipo,
      attributes: (npc.attributes as unknown[]) ?? [],
      skills: (npc.skills as unknown[]) ?? [],
      abilities: (npc.abilities as unknown[]) ?? [],
    }
  }

  const dataJs = `// Auto-generated by Lapse Admin — do not edit manually
// Generated at: ${new Date().toISOString()}

export const data = ${JSON.stringify(playerData, null, 2)};
`

  const npcDataJs = `// Auto-generated by Lapse Admin — do not edit manually
// Generated at: ${new Date().toISOString()}

export const npcData = ${JSON.stringify(npcData, null, 2)};
`

  return NextResponse.json({
    success: true,
    generated_at: new Date().toISOString(),
    player_count: players.length,
    npc_count: npcs.length,
    data_js: dataJs,
    npc_data_js: npcDataJs,
  })
}
